version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-ts-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qo8yjt1ytihm"
s3_prefix = "sam-app-ts-demo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
